# -*- coding: utf-8 -*-
"""task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6eGHhmC3v0-DRvHhnTrb1iQbrVPpaWx
"""

import nltk
nltk.download('stopwords')
import pandas as pd
import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
data = pd.read_csv ("/content/Book1.csv")
data.head()

# Filter for 'Positive' labeled sentences
positive_sentences = data[data['Label'] == 'Positive']

# Display filtered DataFrame
print(positive_sentences)

# Ensure all values in 'Text' column are strings
data['Text'] = data['Text'].astype(str)

# Words to remove
words_to_remove = ['data', 'science']

# Convert text to lowercase
data['Text'] = data['Text'].str.lower()

# Remove numbers
data['Text'] = data['Text'].str.replace(r'\d+', '', regex=True)

# Remove special characters
data['Text'] = data['Text'].str.replace(r'\W+', ' ', regex=True)

# Split into words
data['Text'] = data['Text'].str.split()

# Initialize stop words
stop_words = set(stopwords.words('english'))

# Remove stop words and custom words
data['Text'] = data['Text'].apply(lambda x: [word for word in x if word not in stop_words and word not in words_to_remove])

# Join words back into sentences
data['Text'] = data['Text'].apply(lambda x: ' '.join(x))

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data['Text']) # Use the 'Text' column from the DataFrame
print(X)

bow_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
bow_df

word_freq = bow_df.sum(axis=0)
word_freq

word_freq_df = pd.DataFrame(word_freq, columns=['Frequency'])
word_freq_df = word_freq_df.sort_values(by='Frequency', ascending=False)
word_freq_df = word_freq_df.reset_index().rename(columns={'index': 'Words'})
word_freq_df

word_freq_df.head(15)

# Setting a figure size
plt.figure(figsize=(6, 4))

# Plotting the top 30 most frequent words
plt.bar(word_freq_df['Words'].head(20), word_freq_df['Frequency'].head(20), color='Teal', width=0.4)

# Customizing title and labels
plt.title('Top 30 Most Frequent Words in Text', fontsize=18)
plt.xlabel('Words', fontsize=12)
plt.ylabel('Frequency', fontsize=12)

# Rotating the x-axis labels and adjusting alignment
plt.xticks(rotation=60, ha='right', fontsize=12)

# Increasing the size of y-axis (frequency) numbers
plt.yticks(fontsize=12)

# Adjusting layout for better spacing between plot and labels
plt.tight_layout()

# Adding extra space between the plot and x-axis labels
plt.subplots_adjust(bottom=0.1)

# Showing the plot
plt.show()